-- Copyright (C) 2019  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details, at
-- https://fpgasoftware.intel.com/eula.

-- Generated by Quartus Prime Version 19.1.0 Build 670 09/22/2019 SJ Lite Edition
-- Created on Wed Oct  7 10:33:34 2026

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY FrameDecoder IS
    PORT (
        clock : IN STD_LOGIC;
        reset : IN STD_LOGIC := '0';
        ClockEnable : IN STD_LOGIC := '0';
        StartEvent : IN STD_LOGIC := '0';
        CounterIs47 : IN STD_LOGIC := '0';
        AddressInProgress : OUT STD_LOGIC;
        CommandInProgress : OUT STD_LOGIC;
        ResetCounter : OUT STD_LOGIC
    );
END FrameDecoder;

ARCHITECTURE BEHAVIOR OF FrameDecoder IS
    TYPE type_fstate IS (Idle,AddressSampling,CommandSampling);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,ClockEnable,StartEvent,CounterIs47)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= Idle;
            AddressInProgress <= '0';
            CommandInProgress <= '0';
            ResetCounter <= '0';
        ELSE
            AddressInProgress <= '0';
            CommandInProgress <= '0';
            ResetCounter <= '0';
            CASE fstate IS
                WHEN Idle =>
                    IF (((StartEvent = '1') AND (ClockEnable = '1'))) THEN
                        reg_fstate <= AddressSampling;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= Idle;
                    END IF;

                    CommandInProgress <= '0';

                    AddressInProgress <= '0';

                    ResetCounter <= '1';
                WHEN AddressSampling =>
                    IF (((CounterIs47 = '1') AND (ClockEnable = '1'))) THEN
                        reg_fstate <= CommandSampling;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= AddressSampling;
                    END IF;

                    CommandInProgress <= '0';

                    AddressInProgress <= '1';

                    ResetCounter <= '0';
                WHEN CommandSampling =>
                    IF (((CounterIs47 = '1') AND (ClockEnable = '1'))) THEN
                        reg_fstate <= Idle;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= CommandSampling;
                    END IF;

                    CommandInProgress <= '1';

                    AddressInProgress <= '0';

                    ResetCounter <= '0';
                WHEN OTHERS => 
                    AddressInProgress <= 'X';
                    CommandInProgress <= 'X';
                    ResetCounter <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
